# Generated by Django 4.1.5 on 2023-01-21 06:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/skills_pic')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqamingiz 9 bilan boshlanishi va 12 belgidan iborat bo'lishi kerak", regex='^9\\d{12}$')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='basic.skills'),
        ),
    ]
