# Generated by Django 4.1.5 on 2023-02-11 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_skills_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcourse',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz 9 bilan boshlanishi va 12 ta belgidan oshmasligi lozim. Masalan: 998993451545', regex='^9\\d{12}$')]),
        ),
    ]
